source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1.7'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'coffee-rails', '~> 4.1.0'
gem 'faker'
gem 'foreigner'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'kaminari'
gem 'mysql2'
gem 'nilify_blanks'
gem 'paperclip', '~> 4.2'
gem 'rails', '4.2.0'
gem 'rails-settings-cached'
gem 'ransack'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'quiet_assets'
  gem 'rspec-rails', '~> 3.1'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
