source 'https://rubygems.org'

gem 'bcrypt'
gem 'bootstrap-sass'
gem 'cancancan'
gem 'coffee-rails'
gem 'country_select'
gem 'faker'
gem 'geocoder'
gem 'gmaps4rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'kaminari'
gem 'mysql2'
gem 'nilify_blanks'
gem 'paperclip'
gem 'pg'
gem 'rails', '4.2.3'
gem 'rails-settings-cached'
gem 'ransack'
gem 'sass-rails'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'coveralls', require: false
  gem 'factory_girl_rails'
  gem 'letter_opener_web'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'spring'
  gem 'web-console'
end
